version: '3'

services:

  
  web:
    build: ./django/
    container_name: django
    entrypoint: ["./wait.sh"]
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: djangodb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    depends_on:
      - db

  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: djangodb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    #volumes:
    #  - ./db:/docker-entrypoint-initdb.d/:ro
    volumes:
      - ./docker/data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
  